export interface TradesCsvImportModel {
  txid: string,
  txorderid: string,
  pair: string,
  aclass: string,
  time: string,
  type: string,
  orderprice: string,
  price: string,
  cost: string,
  fee: string,
  vol: string,
  margin: string,
  misc: string,
  ledgers: string,
  posttxid: string,
  poststatuscode: string,
  cprice: string,
  ccost: string,
  cfee: string,
  cvol: string,
  cmargin: string,
  net: string,
  trades: string
}
