import NavbarComponent from "../components/navbar";
import "./global.css";
import { Providers } from "./provider";

export const metadata = {
  title: "HomeWeb - Filmdatenbank",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <div>
            <div className="mx-auto sm:block hidden">
              <NavbarComponent></NavbarComponent>
              {children}
            </div>
            <div className="mx-auto container sm:hidden">
              <NavbarComponent></NavbarComponent>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
