import NavbarComponent from "../components/navbar";
import "./global.css";
import { Providers } from "./provider";
import { gql, type TypedDocumentNode } from "@apollo/client";
import { getClient } from "../lib/apollocient";

export const metadata = {
  title: "HomeWeb - Filmdatenbank",
  description: "Generated by create-nx-workspace",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const nextAuthUrl = process.env.NEXTAUTH_URL; // runtime env on server
  const appVersion = await fetchAppVersion();
  return (
    <html lang="en">
      {/* let the page occupy the whole viewport */}
      <body className="min-h-screen">
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }} nextAuthUrl={nextAuthUrl}>
          {/* ONE wrapper – full width always */}
          <div className="w-screen min-h-screen overflow-x-hidden">
            <NavbarComponent appVersion={appVersion} />

            {/* content: narrow-ish on phones, full width from sm+ */}
            <main className="w-full px-0">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}

type SystemInfoResult = {
  systemInfo?: {
    appVersion?: string;
  };
};

const systemInfoQuery: TypedDocumentNode<SystemInfoResult> = gql`
  query GetSystemInfo {
    systemInfo {
      appVersion
    }
  }
`;

async function fetchAppVersion(): Promise<string | undefined> {
  try {
    const { data } = await getClient().query<SystemInfoResult>({
      query: systemInfoQuery,
    });
    return data?.systemInfo?.appVersion?.trim();
  } catch (error) {
    console.warn("Navbar version unavailable", error);
    return undefined;
  }
}
