import NavbarComponent from "../components/navbar";
import "./global.css";
import { Providers } from "./provider";

export const metadata = {
  title: "HomeWeb - Filmdatenbank",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* let the page occupy the whole viewport */}
      <body className="min-h-screen">
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          {/* ONE wrapper – full width always */}
          <div className="w-screen min-h-screen overflow-x-hidden">
            <NavbarComponent />

            {/* content: narrow-ish on phones, full width from sm+ */}
            <main className="w-full px-0">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
