import { test, expect } from "@playwright/test";

test("basic search for luca, toggle seen today, toggle flag, toggle fav", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/movies");
  await expect(page.getByRole("navigation").locator("div").filter({ hasText: "Filmdatenbank" })).toBeVisible();
  await expect(page.locator(".inline-flex.w-full.items-center").first()).toBeVisible();
  await expect(page.getByRole("button").nth(2)).toBeVisible();
  await expect(page.getByRole("button", { name: "Filter" })).toBeVisible();
  await page.getByRole("textbox", { name: "Suche (Ergebnisse: 0)" }).click();
  await page.getByRole("textbox", { name: "Suche (Ergebnisse: 0)" }).fill("luca");
  await page.getByRole("textbox", { name: "Suche (Ergebnisse: 0)" }).press("Enter");
  await expect(page.getByText("Luca", { exact: true })).toBeVisible();
  await expect(page.getByText("noch nicht gesehen").first()).toBeVisible();
  await expect(page.getByRole("link", { name: "Movie Cover" }).first()).toBeVisible();
  await expect(page.getByText("Der Disney Pixar")).toBeVisible();
  await expect(page.getByText("Animation", { exact: true })).toBeVisible();
  await expect(page.getByText("Comedy")).toBeVisible();
  await expect(page.getByText("Family")).toBeVisible();
  await expect(page.getByText("Fantasy").first()).toBeVisible();
  await expect(page.getByText("95 min")).toBeVisible();
  await expect(page.getByText("Bewertung 8.2")).toBeVisible();
  await expect(page.getByTestId("seen-today-button").first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Datum auswählen" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Details" }).first()).toBeVisible();
  await expect(page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").first()).toBeVisible();
  await expect(page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").nth(1)).toBeVisible();
  await expect(page.getByText("Blu-ray").first()).toBeVisible();
  await expect(page.getByText("R26F1D08")).toBeVisible();
  await page.getByTestId("seen-today-button").first().click();
  await expect(page.getByText("x gesehen")).toBeVisible();
  await expect(page.getByTestId("seen_date_duration_chip").getByText("Heute gesehen")).toBeVisible();
  await expect(page.getByRole("button", { name: "close chip" })).toBeVisible();
  await page.getByRole("button", { name: "close chip" }).click();
  await page.getByRole("button", { name: "Löschen" }).click();
  await expect(page.getByText("noch nicht gesehen").first()).toBeVisible();
  await page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").first().click();
  await page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").nth(1).click();
  await expect(page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").first()).toBeVisible();
  await expect(page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").nth(1)).toBeVisible();
  await page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").first().click();
  await page.locator("div").filter({ hasText: /^Blu-rayR26F1D08$/ }).getByRole("button").nth(1).click();
});
